### ISSUE TITLE
TODO: Make pyrokinetics IMAS compliant

### ISSUE THREAD

**Issue by bpatel2107** [pyro-kinetics/pyrokinetics#10]
Make an interface between pyrokinetics and IMAS to further diversify the application of pyrokinetics

**Comment by ZedThree** [comment]
[OMAS](https://gafusion.github.io/omas/index.html) might be useful here

**Comment by fcasson** [comment]
Or GKDB:  https://gitlab.com/gkdb/gkdb/-/wikis/home

**Comment by bpatel2107** [comment]
Just bumping this issue. 

We should discuss whether we want to switch over our naming conventions to match imas

**Comment by bpatel2107** [comment]
Done in #113
